version: "3.5"

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongodb
    networks:
      - MONGO
  app:
    container_name: app
    build:
      context: ./app
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - MONGO
    depends_on:
      - mongo
    restart: on-failure

networks:
  MONGO:
    driver: bridge